databases:
  - name: linktree_rails
    databaseName: linktree_rails
    user: rjkush17
    plan: free

services:
  - type: web
    name: linktree_rails
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: linktree_rails
          property: connectionString
      - key: RAILS_MASTER_KEY
        value: 1f8bbfb2f7bf1f5c8b6938781dc24bfe
      - key: WEB_CONCURRENCY
        value: 2 # sensible default