default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: Rishabh@17
  host: localhost
  port: 5432

development:
  <<: *default
  database: mydatabase_development
  username: postgres
  password: Rishabh@17

test:
  <<: *default
  database: mydatabase_test
  username: postgres
  password: Rishabh@17

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>